const enum ActionLog {
  ACCOUNT_SIGNUP = "REGISTERED AN ACCOUNT",
  ACCOUNT_SIGNIN = "LOGGED IN",
  ACCOUNT_LOGOUT = "LOGGED OUT",
  ACCOUNT_LOCKED = "ACCOUNT GOT LOCKED",

  VERIFIED_EMAIL = "VERIFIED EMAIL",
  RESET_PASSWORD = "RESET PASSWORD",
  CHANGE_PASSWORD = "CHANGED PASSWORD",

  UPDATE_PROFILE = "PROFILE UPDATED",
  ENABLE_2FA = "ENABLED TWO FACTOR AUTHENTICATION",
  DISABLE_2FA = "DISABLED TWO FACTOR AUTHENTICATION",

  RESEND_VERIFICATION_EMAIL = "RESEND VERIFICATION EMAIL",
  RESEND_PASS_RESET_EMAIL = "RESEND PASSWORD RESET EMAIL",
}

export { ActionLog };
