const enum ErrorCode {
  AUTH_TOKEN_INVALID = "AUTH_INVALID_TOKEN",
  AUTH_TOKEN_NOT_FOUND = "AUTH_TOKEN_NOT_FOUND",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_HAS_EXPIRED",
  AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",
  AUTH_NOT_FOUND = "AUTH_NOT_FOUND",

  AUTH_TOO_MANY_ATTEMPTS = "AUTH_TOO_MANY_ATTEMPTS",
  AUTH_UNAUTHORIZED_ACCESS = "AUTH_UNAUTHORIZED_ACCESS",

  // Authentication Errors
  AUTH_INVALID_CREDENTIALS = "INVALID CREDENTIALS",
  AUTH_ACCOUNT_LOCKED = "ACCOUNT IS LOCKED",
  AUTH_EMAIL_ALREADY_EXISTS = "EMAIL ALREADY IN USE",
  AUTH_EMAIL_UNVERIFIED = "EMAIL IS NOT VERIFIED",
  AUTH_2FA_REQUIRED = "2FA IS REQUIRED",
  AUTH_2FA_INVALID_CODE = "INVALID 2-FACTOR CODE",

  // Access Control Errors
  ACCESS_FORBIDDEN = "ACCESS_FORBIDDEN",
  ACCESS_UNAUTHORIZED = "ACCESS_UNAUTHORIZED",

  // Validation and Resource Errors
  VALIDATION_ERROR = "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",

  // System Errors
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  VERIFICATION_ERROR = "VERIFICATION_ERROR",
  METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED",
  INVALID_DATA = "INVALID_REQUEST_DATA",
  DATA_NOT_FOUND = "DATA_NOT_FOUND",

  INVALID_LINK = "INVALID LINK",
  EXPIRED_LINK = "LINK HAS EXPIRED",
  INVALID_CODE = "INVALID CODE",
  EXPIRED_CODE = "CODE HAS EXPIRED",
  EMAIL_ALREADY_VERIFIED = "EMAIL ALREADY VERIFIED",
}

export { ErrorCode };
