const enum SuccessCode {
  AUTH_SIGNUP = "USER REGISTRATION SUCCESSFUL",
  AUTH_SIGNIN = "USER LOGIN SUCCESSFUL",
  AUTH_LOGOUT = "USER LOGOUT SUCCESSFUL",

  VALID_LINK = "VALID_LINK",
  VERIFICATION_SUCCESS = "EMAIL VERIFICATION SUCCESSFUL",
  PASSWORD_RESET = "PASSWORD RESET SUCCESSFUL",
  PASSWORD_UPDATE = "PASSWORD UPDATE SUCCESSFUL",

  VERIFICATION_CODE_RESET = "CODE HAS BEEN RESET",
}

export { SuccessCode };
