const enum SuccessCode {
  AUTH_SIGNUP = "USER REGISTRATION SUCCESSFUL",
  AUTH_SIGNIN = "USER LOGIN SUCCESSFUL",
  AUTH_LOGOUT = "USER LOGOUT SUCCESSFUL",

  VALID_LINK = "VALID_LINK",
  EMAIL_VERIFICATION = "EMAIL VERIFICATION SUCCESSFUL",
  PASSWORD_RESET = "PASSWORD RESET SUCCESSFUL",
  PASSWORD_UPDATE = "PASSWORD UPDATE SUCCESSFUL",
}

export { SuccessCode };
